"""update lesson, check

Revision ID: d6ccc0a46435
Revises: 938f10f7bc61
Create Date: 2024-09-06 13:19:10.569928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ccc0a46435'
down_revision: Union[str, None] = '938f10f7bc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Checks', sa.Column('trainer_comments', sa.Text(), nullable=True))
    op.add_column('Checks', sa.Column('rewards', sa.Text(), nullable=True))
    op.add_column('Lessons', sa.Column('status', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'Notifications', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Notifications', type_='unique')
    op.drop_column('Lessons', 'status')
    op.drop_column('Checks', 'rewards')
    op.drop_column('Checks', 'trainer_comments')
    # ### end Alembic commands ###
